---
downloads: ~/.ansible-downloads/

configure_dock: true
dockitems_remove:
  - Maps
  - TV
  - Podcasts
  - News
  - 'App Store'
  - Music
dockitems_persist:
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 5
  - name: "ITerm"
    path: "/Applications/ITerm.app/"
    pos: 3
  - name: "1Password"
    path: "/Applications/1Password.app/"
    pos: 4


homebrew_installed_packages:
  - git
  - github/gh/gh
  - node
  - nvm
  - htop
  - rust
  - awscli

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - 1password
  - dbeaver-community
  - docker
  - firefox
  - google-chrome
  - slack
  - transmit
  - visual-studio-code
  - local
  - insomnia
  - postman
  - openvpn-connect
  - whatsapp
  - aldente
  - caffeine
  - github
  - iterm2
  - spotify

mas_installed_apps: []
